// <auto-generated />
using System;
using Filas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filas.Migrations
{
    [DbContext(typeof(FilasDbContext))]
    [Migration("20220923115751_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Filas.DTOs.Mesas", b =>
                {
                    b.Property<int>("ID_MESA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MESA"), 1L, 1);

                    b.Property<string>("DS_MESA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_MESA");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Filas.DTOs.Reservas", b =>
                {
                    b.Property<int>("ID_REVERSA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_REVERSA"), 1L, 1);

                    b.Property<DateTime>("HORA_RESERVA")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_MESA")
                        .HasColumnType("int");

                    b.Property<string>("NOME_RESERVA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QTD_PESSOAS")
                        .HasColumnType("int");

                    b.HasKey("ID_REVERSA");

                    b.HasIndex("ID_MESA");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Filas.DTOs.Reservas", b =>
                {
                    b.HasOne("Filas.DTOs.Mesas", "Mesas")
                        .WithMany()
                        .HasForeignKey("ID_MESA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesas");
                });
#pragma warning restore 612, 618
        }
    }
}
